### ISSUE TITLE
The changes in common-files folder

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seedlabs-chinese#8]
Do you think it should be overwritten by and translated from the newest version?

**Comment by kevin-w-du** [comment]
Currently, in this repo, the common-files folder only has `header.tex` and `copyright.text`. These two files are pretty much the same, so you can overwrite them with the newest version. There are many new files in ubuntu20.04. I also created a branch called ubuntu16.04 in this repo, just to make a backup.
